#!/bin/bash
umask 022

KITS_CONFIG_PATH=~/.kits_path
SETUP_DIR=$(cd $(dirname $0); pwd)

echo "export KITS=$SETUP_DIR" > $KITS_CONFIG_PATH

. $KITS_CONFIG_PATH
. $KITS/shell/common.sh

# profile处理
_kits_symbolic_link $KITS/dotfiles/bash_profile.sh ~/.bash_profile
_kits_symbolic_link $KITS/dotfiles/bashrc.sh ~/.bashrc

# sublime text
_kits_symbolic_link "/Applications/Sublime Text 2.app/Contents/SharedSupport/bin/subl" $KITS/bin/subl

# 下列需要root权限
if [[ "$(whoami)" = "root" ]]; then
    _kits_symbolic_link $KITS/dotfiles/hosts /etc/hosts
fi

echo "Kits installed."
